name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: deploy_on_vercel
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Debug - Vérifier la structure du repo
        run: ls -al  # ✅ Vérifie la structure des dossiers

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Debug - Vérifier package.json et scripts npm
        run: npm run
        working-directory: App
      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build 
        working-directory: App

      - name: Debug - Vérifier le contenu du build
        run: ls -al App/dist

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
